In [3]:
import numpy as np

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
type(iris)

sklearn.utils.Bunch

In [7]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
X = iris.data

In [9]:
X # numpy array with four measurments (sepal length, sepal width, petal length, petal width)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = iris.target

In [11]:
y # classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
# this is how keras will setup the classes from 'y'
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [13]:
from keras.utils import to_categorical

In [14]:
y = to_categorical(y)

In [17]:
y.shape

(150, 3)

In [18]:
# step 1: Train the data that you have with sklearn
from sklearn.model_selection import train_test_split

In [19]:
# X = 4 measurments, y = 3 classes models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [23]:
# y_test

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
# how MinMaxScaler works
np.array([5,10,15,20])/20 # [min, x, y, max]/max = (ranges between 0 to 1)

array([0.25, 0.5 , 0.75, 1.  ])

In [26]:
scaler_object = MinMaxScaler()

In [27]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [28]:
scaled_X_train = scaler_object.transform(X_train)

In [29]:
scaled_X_test = scaler_object.transform(X_test)

In [31]:
# all the values are now between 0 and 1 (helps neural networkw to evade large symbiosis growing)
# scaled_X_train

In [32]:
# setp 2: Build a network with keras
from keras.models import Sequential # Model to use. In this case sequencial, to add a sequence of layers
from keras.layers import Dense # layers to use, in this case, Dense layers

In [33]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax')) # [0.2,0.3,0.5]
# compile the model
model.compile(
    loss='categorical_crossentropy', # what are we performing? in this case categorical data
    optimizer='adam',
    metrics=['accuracy'] # what are we trainig? what are we gonig to report back?. In this case, accuracy.
)

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [35]:
 model.fit(scaled_X_train, y_train, epochs=150, verbose=2) # train our model with our scale data

Epoch 1/150
4/4 - 0s - loss: 1.0969 - accuracy: 0.3500
Epoch 2/150
4/4 - 0s - loss: 1.0920 - accuracy: 0.3500
Epoch 3/150
4/4 - 0s - loss: 1.0874 - accuracy: 0.3600
Epoch 4/150
4/4 - 0s - loss: 1.0827 - accuracy: 0.3700
Epoch 5/150
4/4 - 0s - loss: 1.0783 - accuracy: 0.4200
Epoch 6/150
4/4 - 0s - loss: 1.0738 - accuracy: 0.4800
Epoch 7/150
4/4 - 0s - loss: 1.0698 - accuracy: 0.5700
Epoch 8/150
4/4 - 0s - loss: 1.0657 - accuracy: 0.6200
Epoch 9/150
4/4 - 0s - loss: 1.0616 - accuracy: 0.6400
Epoch 10/150
4/4 - 0s - loss: 1.0574 - accuracy: 0.6600
Epoch 11/150
4/4 - 0s - loss: 1.0533 - accuracy: 0.6600
Epoch 12/150
4/4 - 0s - loss: 1.0489 - accuracy: 0.6600
Epoch 13/150
4/4 - 0s - loss: 1.0445 - accuracy: 0.6600
Epoch 14/150
4/4 - 0s - loss: 1.0402 - accuracy: 0.6600
Epoch 15/150
4/4 - 0s - loss: 1.0355 - accuracy: 0.6600
Epoch 16/150
4/4 - 0s - loss: 1.0304 - accuracy: 0.6600
Epoch 17/150
4/4 - 0s - loss: 1.0251 - accuracy: 0.6600
Epoch 18/150
4/4 - 0s - loss: 1.0195 - accuracy: 0.6600
E