In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
type(iris)

sklearn.utils.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
X = iris.data

In [8]:
X # numpy array with four measurments (sepal length, sepal width, petal length, petal width)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y = iris.target

In [10]:
y # classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# this is how keras will setup the classes from 'y'
# class 0 --> [1,0,0]
# class 1 --> [0,1,0]
# class 2 --> [0,0,1]

In [12]:
from keras.utils import to_categorical

In [13]:
y = to_categorical(y)

In [14]:
y.shape

(150, 3)

In [15]:
# step 1: Train the data that you have with sklearn
from sklearn.model_selection import train_test_split

In [16]:
# X = 4 measurments, y = 3 classes models
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
# y_test

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
# how MinMaxScaler works
np.array([5,10,15,20])/20 # [min, x, y, max]/max = (ranges between 0 to 1)

array([0.25, 0.5 , 0.75, 1.  ])

In [20]:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [22]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_test = scaler_object.transform(X_test)

In [24]:
# all the values are now between 0 and 1 (helps neural networkw to evade large symbiosis growing)
# scaled_X_train

In [25]:
# setp 2: Build a network with keras
from keras.models import Sequential # Model to use. In this case sequencial, to add a sequence of layers
from keras.layers import Dense # layers to use, in this case, Dense layers

In [26]:
model = Sequential()
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(8,input_dim=4,activation='relu'))
model.add(Dense(3,activation='softmax')) # [0.2,0.3,0.5]
# compile the model
model.compile(
    loss='categorical_crossentropy', # what are we performing? in this case categorical data
    optimizer='adam',
    metrics=['accuracy'] # what are we trainig? what are we gonig to report back?. In this case, accuracy.
)

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [28]:
 model.fit(scaled_X_train, y_train, epochs=150, verbose=2) # train our model with our scale data

Epoch 1/150
4/4 - 0s - loss: 1.0921 - accuracy: 0.3700
Epoch 2/150
4/4 - 0s - loss: 1.0880 - accuracy: 0.3700
Epoch 3/150
4/4 - 0s - loss: 1.0854 - accuracy: 0.3700
Epoch 4/150
4/4 - 0s - loss: 1.0826 - accuracy: 0.3700
Epoch 5/150
4/4 - 0s - loss: 1.0799 - accuracy: 0.3700
Epoch 6/150
4/4 - 0s - loss: 1.0772 - accuracy: 0.3700
Epoch 7/150
4/4 - 0s - loss: 1.0746 - accuracy: 0.3700
Epoch 8/150
4/4 - 0s - loss: 1.0721 - accuracy: 0.3700
Epoch 9/150
4/4 - 0s - loss: 1.0697 - accuracy: 0.3600
Epoch 10/150
4/4 - 0s - loss: 1.0670 - accuracy: 0.3400
Epoch 11/150
4/4 - 0s - loss: 1.0647 - accuracy: 0.3400
Epoch 12/150
4/4 - 0s - loss: 1.0619 - accuracy: 0.3400
Epoch 13/150
4/4 - 0s - loss: 1.0596 - accuracy: 0.3400
Epoch 14/150
4/4 - 0s - loss: 1.0568 - accuracy: 0.3400
Epoch 15/150
4/4 - 0s - loss: 1.0542 - accuracy: 0.3400
Epoch 16/150
4/4 - 0s - loss: 1.0514 - accuracy: 0.3400
Epoch 17/150
4/4 - 0s - loss: 1.0486 - accuracy: 0.3400
Epoch 18/150
4/4 - 0s - loss: 1.0458 - accuracy: 0.3400
E

In [29]:
# part 2: Predictions with our models
model.predict_classes(scaled_X_test)

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

In [30]:
model.predict(scaled_X_test)

array([[2.9981606e-02, 4.5531443e-01, 5.1470393e-01],
       [9.4843727e-01, 4.1365497e-02, 1.0197180e-02],
       [6.0734467e-04, 2.5857285e-01, 7.4081981e-01],
       [2.8673463e-02, 4.6224910e-01, 5.0907749e-01],
       [1.2149183e-02, 4.0328020e-01, 5.8457065e-01],
       [9.1524005e-01, 6.6065446e-02, 1.8694513e-02],
       [1.1065453e-01, 4.9598494e-01, 3.9336056e-01],
       [3.0810935e-03, 3.4755144e-01, 6.4936745e-01],
       [8.1888214e-03, 3.7764022e-01, 6.1417103e-01],
       [6.2504895e-02, 4.8336643e-01, 4.5412871e-01],
       [8.9725517e-03, 4.1099253e-01, 5.8003485e-01],
       [9.1116911e-01, 6.7889325e-02, 2.0941600e-02],
       [9.4186407e-01, 4.5683686e-02, 1.2452220e-02],
       [9.1876185e-01, 6.2606476e-02, 1.8631702e-02],
       [9.5881057e-01, 3.2998633e-02, 8.1907678e-03],
       [3.8657252e-02, 4.8407695e-01, 4.7726578e-01],
       [2.3433266e-03, 3.4231642e-01, 6.5534025e-01],
       [5.6019135e-02, 4.7734591e-01, 4.6663487e-01],
       [4.0415037e-02, 4.780

In [31]:
predictions = model.predict_classes(scaled_X_test)

In [32]:
y_test.argmax(axis=1) # adapt y_test to the scaled predictions format

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [33]:
predictions

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

In [34]:
# now we just compared them
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [35]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0,  7,  8],
       [ 0,  0, 16]])

In [36]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.47      0.64        15
           2       0.67      1.00      0.80        16

    accuracy                           0.84        50
   macro avg       0.89      0.82      0.81        50
weighted avg       0.89      0.84      0.83        50



In [37]:
accuracy_score(y_test.argmax(axis=1), predictions)

0.84

In [38]:
# save our model
model.save('myfirstmodel.h5')

In [39]:
# load our model
from keras.models import load_model

In [40]:
new_model = load_model('myfirstmodel.h5')

In [42]:
# after loading it, we can use it as before
predictions2 = new_model.predict_classes(scaled_X_test)

In [43]:
predictions2

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])

In [44]:
predictions

array([2, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 2, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 1, 0, 0, 0, 2, 1, 2, 0,
       0, 1, 2, 2, 2, 2])