In [4]:
import pickle
import numpy as np

In [5]:
with open('train_qa.txt', 'rb') as f:
    train_data = pickle.load(f)

In [6]:
with open('test_qa.txt', 'rb') as f:
    test_data = pickle.load(f)

In [7]:
type(test_data)

list

In [8]:
type(train_data)

list

In [9]:
len(train_data)

10000

In [10]:
len(test_data)

1000

In [11]:
train_data[0] # train data sentences followed with a questin and an answer

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [12]:
# story
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [13]:
# question
' '.join(train_data[0][1])

'Is Sandra in the hallway ?'

In [14]:
# answer
train_data[0][2]

'no'

In [15]:
# create a vocabulary
all_data = test_data + train_data

In [16]:
len(all_data)

11000

In [17]:
set(train_data[0][0]) # turn list into a set

{'.',
 'Mary',
 'Sandra',
 'bathroom',
 'bedroom',
 'journeyed',
 'moved',
 'the',
 'to'}

In [18]:
vocab = set()

for story, question, answer in all_data:
    # unite all sets into one set (it organize values and remove repeated ones)
    # https://www.programiz.com/python-programming/methods/set/union
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

In [19]:
vocab.add('no')

In [20]:
vocab.add('yes')

In [21]:
# set of all the possible vocab words
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [22]:
vocab_len = len(vocab) + 1 # (+ 1 is the placeholder that we will use later on, by deffect is 0)

In [23]:
vocab_len

38

In [24]:
# LONGEST STORY
# the all stories length
all_story_lens = [len(data[0]) for data in all_data]

In [25]:
max_story_len = max(all_story_lens) # get the max length

In [26]:
# LONGEST QUESTION
# get max question length too
all_question_lens = [len(data[1]) for data in all_data]
max_question_len = max(all_question_lens)

In [27]:
max_question_len

6

In [28]:
# part 2: Vectorizing stories
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [29]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [30]:
tokenizer.word_index

{'put': 1,
 'picked': 2,
 'journeyed': 3,
 'moved': 4,
 '.': 5,
 'milk': 6,
 'yes': 7,
 'back': 8,
 'is': 9,
 '?': 10,
 'football': 11,
 'mary': 12,
 'no': 13,
 'there': 14,
 'went': 15,
 'bathroom': 16,
 'took': 17,
 'dropped': 18,
 'sandra': 19,
 'discarded': 20,
 'office': 21,
 'hallway': 22,
 'kitchen': 23,
 'got': 24,
 'grabbed': 25,
 'daniel': 26,
 'to': 27,
 'down': 28,
 'left': 29,
 'bedroom': 30,
 'apple': 31,
 'up': 32,
 'john': 33,
 'in': 34,
 'the': 35,
 'travelled': 36,
 'garden': 37}

In [31]:
# tokenization for stories, questions and answers
train_story_text = []
train_question_text = []
train_answers = []

In [32]:
# separate each of them
for story, question, answer in train_data:
    train_story_text.append(story)
    train_question_text.append(question)
    train_answers.append(answer)

In [33]:
# turning each text's word into its matching word sequence (check tokenizer.word_index)
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [34]:
len(train_story_seq)

10000

In [37]:
len(train_story_text)

10000

In [38]:
train_story_seq # story vector

[[12, 4, 27, 35, 16, 5, 19, 3, 27, 35, 30, 5],
 [12,
  4,
  27,
  35,
  16,
  5,
  19,
  3,
  27,
  35,
  30,
  5,
  12,
  15,
  8,
  27,
  35,
  30,
  5,
  26,
  15,
  8,
  27,
  35,
  22,
  5],
 [12,
  4,
  27,
  35,
  16,
  5,
  19,
  3,
  27,
  35,
  30,
  5,
  12,
  15,
  8,
  27,
  35,
  30,
  5,
  26,
  15,
  8,
  27,
  35,
  22,
  5,
  19,
  15,
  27,
  35,
  23,
  5,
  26,
  15,
  8,
  27,
  35,
  16,
  5],
 [12,
  4,
  27,
  35,
  16,
  5,
  19,
  3,
  27,
  35,
  30,
  5,
  12,
  15,
  8,
  27,
  35,
  30,
  5,
  26,
  15,
  8,
  27,
  35,
  22,
  5,
  19,
  15,
  27,
  35,
  23,
  5,
  26,
  15,
  8,
  27,
  35,
  16,
  5,
  26,
  2,
  32,
  35,
  11,
  14,
  5,
  26,
  15,
  27,
  35,
  30,
  5],
 [12,
  4,
  27,
  35,
  16,
  5,
  19,
  3,
  27,
  35,
  30,
  5,
  12,
  15,
  8,
  27,
  35,
  30,
  5,
  26,
  15,
  8,
  27,
  35,
  22,
  5,
  19,
  15,
  27,
  35,
  23,
  5,
  26,
  15,
  8,
  27,
  35,
  16,
  5,
  26,
  2,
  32,
  35,
  11,
  14,
  5,
  26,
  15,
  27,


In [40]:
# create method to vectorize stories, questions and answers (same steps as before)
def vectorize_stories(data, word_index=tokenizer.word_index, max_story_len=max_story_len, max_question_len=max_question_len):
    
    # STORIES = X
    X = []
    # QUESTIONS Xq
    Xq = []
    # Y CORRECT ANSWER (yes/no)
    Y = []
    
    for story, query, answer in data:
        
        # for each story
        # [23, 14, ...]
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in query]
        
        y = np.zeros(len(word_index)+1)
        
        y[word_index[answer]] = 1
        
        X.append(x)
        Xq.append(xq)
        Y.append(y)
    
    return (pad_sequences(X, maxlen=max_story_len), pad_sequences(Xq, maxlen=max_question_len), np.array(Y))

In [41]:
# now we have our data formatted (Vectorized) and we can use it to create our models
inputs_train, queries_train, answers_train = vectorize_stories(train_data)

In [42]:
inputs_test, queries_tests, answers_test = vectorize_stories(test_data)

In [43]:
inputs_test

array([[ 0,  0,  0, ..., 35, 30,  5],
       [ 0,  0,  0, ..., 35, 37,  5],
       [ 0,  0,  0, ..., 35, 37,  5],
       ...,
       [ 0,  0,  0, ..., 35, 31,  5],
       [ 0,  0,  0, ..., 35, 37,  5],
       [ 0,  0,  0, ..., 31, 14,  5]], dtype=int32)

In [44]:
answers_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [45]:
tokenizer.word_index['yes'] # position of the answer yes

7

In [46]:
tokenizer.word_index['no'] # position of the answer no

13

In [48]:
sum(answers_test) # here you can see the two previous indexes

array([  0.,   0.,   0.,   0.,   0.,   0.,   0., 497.,   0.,   0.,   0.,
         0.,   0., 503.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [49]:
sum(answers_test)[7]

497.0

In [50]:
sum(answers_test)[13]

503.0